### ISSUE TITLE
Suggestion/Request

### ISSUE THREAD

**Issue by ghost** [ImTiara/NoPerformanceStats#3]
Please add an option to disable the stats tag on nameplates (and center the trust tag to be in the middle if it doesn't do it itself) and the avatar stats button in the avatar page while this mod is active.
![image](https://user-images.githubusercontent.com/83312981/122114037-af70cc80-cdd7-11eb-9076-5cbbd7e988c4.png)
![image](https://user-images.githubusercontent.com/83312981/122114074-b8fa3480-cdd7-11eb-9f69-487a0e121e8f.png)

**Comment by ImTiara** [comment]
This was planned and will come very soon
